<?php

namespace Customize\Repository;

use Eccube\Entity\Product; #ProductのDBから取得する為
use Symfony\Bridge\Doctrine\RegistryInterface; #Entityと連携する為
use Eccube\Repository\AbstractRepository; #Repositoryを拡張する為

/**
 * CustomizeProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomizeProductRepository extends AbstractRepository
{
    /**
     * CustomizeProductRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Product::class); #EntityのProductを呼び出している
    }
    
    /**
     * 全検索
     *
     * @return Products|array
     */
    public function customFindAll() #関数名(何でも良い)
    {
        $qb = $this->createQueryBuilder('p'); #何でも良いがproductの頭文字を取ってます。
        $products = $qb
            ->getQuery() #作成したクエリを取得
            ->getResult(); #実行
        return $products;
    }
}
